---
# oracle-jdk8, tomcat8

- hosts: webservers
  vars:
    ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_rsa
    ansible_user: jenkins
    ansible_become: yes

  roles:
    -oracle-jdk8
    - tomcat8

